insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1001,'KB', 'GET AWS CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1002,'KB', 'GET MATHS CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1003,'KB', 'GET COMS CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1004,'KB', 'GET ETHICAL HACKING CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1005,'Wits', 'GET COMSI CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1006,'Wits', 'GET AI CERTIFIED',CURRENT_DATE(), false);

insert into todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1007,'Wits', 'GET JAVA CERTIFIED',CURRENT_DATE(), false);